libntoh: libntoh/common.c File Reference
common.c File Reference
#include <stdlib.h>
#include <libntoh.h>
Functions
_HIDDEN phtable_t htable_map (size_t size)
_HIDDEN int htable_insert (phtable_t ht, unsigned int key, void *val)
_HIDDEN void * htable_find (phtable_t ht, unsigned int key)
_HIDDEN void * htable_remove (phtable_t ht, unsigned int key)
_HIDDEN unsigned int htable_count (phtable_t ht)
_HIDDEN unsigned int htable_first (phtable_t ht)
_HIDDEN void htable_destroy (phtable_t *ht)
_HIDDEN void lock_access (pntoh_lock_t lock)
Access locking.
_HIDDEN void unlock_access (pntoh_lock_t lock)
Access unlocking.
_HIDDEN void free_lockaccess (pntoh_lock_t lock)
Function Documentation
_HIDDEN void free_lockaccess (pntoh_lock_t lock)
Definition at line 229 of file common.c.
References ntoh_lock_t::mutex, and ntoh_lock_t::pcond.
Referenced by ntoh_ipv4_exit(), and ntoh_tcp_exit().
_HIDDEN unsigned int htable_count (phtable_t ht)
Definition at line 143 of file common.c.
References htable_t::table, and htable_t::table_size.
Referenced by ntoh_ipv4_count_flows(), and ntoh_tcp_count_streams().
_HIDDEN void htable_destroy (phtable_t * ht)
Definition at line 176 of file common.c.
_HIDDEN void* htable_find (phtable_t ht, unsigned int key)
Definition at line 85 of file common.c.
References htable_t::table, and htable_t::table_size.
Referenced by ntoh_ipv4_find_flow(), and ntoh_tcp_find_stream().
_HIDDEN unsigned int htable_first (phtable_t ht)
Definition at line 159 of file common.c.
References htable_t::table, and htable_t::table_size.
_HIDDEN int htable_insert (phtable_t ht, unsigned int key, void * val)
Definition at line 53 of file common.c.
References htable_t::table, and htable_t::table_size.
Referenced by ntoh_ipv4_new_flow(), and ntoh_tcp_new_stream().
_HIDDEN phtable_t htable_map (size_t size)
HASH TABLE
Definition at line 38 of file common.c.
References htable_t::table, and htable_t::table_size.
Referenced by ntoh_ipv4_new_session(), and ntoh_tcp_new_session().
_HIDDEN void* htable_remove (phtable_t ht, unsigned int key)
Definition at line 106 of file common.c.
References htable_t::table, and htable_t::table_size.
_HIDDEN void lock_access (pntoh_lock_t lock)
Access locking.
ACCESS LOCKING
Definition at line 203 of file common.c.
References ntoh_lock_t::mutex, ntoh_lock_t::pcond, and ntoh_lock_t::use.
Referenced by ntoh_ipv4_add_fragment(), ntoh_ipv4_count_flows(), ntoh_ipv4_exit(), ntoh_ipv4_find_flow(), ntoh_ipv4_free_flow(), ntoh_ipv4_free_session(), ntoh_ipv4_get_size(), ntoh_ipv4_new_flow(), ntoh_ipv4_new_session(), ntoh_tcp_add_segment(), ntoh_tcp_count_streams(), ntoh_tcp_exit(), ntoh_tcp_find_stream(), ntoh_tcp_free_session(), ntoh_tcp_free_stream(), ntoh_tcp_get_size(), ntoh_tcp_new_session(), and ntoh_tcp_new_stream().
_HIDDEN void unlock_access (pntoh_lock_t lock)
Access unlocking.
Definition at line 217 of file common.c.
References ntoh_lock_t::mutex, ntoh_lock_t::pcond, and ntoh_lock_t::use.
Referenced by ntoh_ipv4_add_fragment(), ntoh_ipv4_count_flows(), ntoh_ipv4_exit(), ntoh_ipv4_find_flow(), ntoh_ipv4_free_flow(), ntoh_ipv4_free_session(), ntoh_ipv4_get_size(), ntoh_ipv4_new_flow(), ntoh_ipv4_new_session(), ntoh_tcp_add_segment(), ntoh_tcp_count_streams(), ntoh_tcp_exit(), ntoh_tcp_find_stream(), ntoh_tcp_free_session(), ntoh_tcp_free_stream(), ntoh_tcp_get_size(), ntoh_tcp_new_session(), and ntoh_tcp_new_stream().