libntoh: libntoh/ipv4defrag.c File Reference
ipv4defrag.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <netinet/ip.h>
#include <sys/time.h>
#include <libntoh.h>
Macros
#define __FAVOR_BSD
#define NTOH_GET_IPV4_FRAGMENT_OFFSET(offset) (8*(ntohs(offset)&IP_OFFMASK))
#define IS_SET(a, b) (a & b)
Functions
unsigned int ntoh_ipv4_get_size (pntoh_ipv4_session_t session)
API to get the size of the flows table (max allowed flows)
unsigned int ntoh_ipv4_get_tuple4 (struct ip *ip, pntoh_ipv4_tuple4_t tuple)
API to get a tuple4.
pntoh_ipv4_flow_t ntoh_ipv4_find_flow (pntoh_ipv4_session_t session, pntoh_ipv4_tuple4_t tuple4)
Finds an IP flow.
pntoh_ipv4_flow_t ntoh_ipv4_new_flow (pntoh_ipv4_session_t session, pntoh_ipv4_tuple4_t tuple4, pipv4_dfcallback_t function, void *udata, unsigned int *error)
Adds a new IPv4 flow.
void ntoh_ipv4_free_flow (pntoh_ipv4_session_t session, pntoh_ipv4_flow_t *flow, unsigned short reason)
Frees an IPv4 flow.
int ntoh_ipv4_add_fragment (pntoh_ipv4_session_t session, pntoh_ipv4_flow_t flow, struct ip *iphdr, size_t len)
Adds a new IPv4 fragment to a given flow.
unsigned int ntoh_ipv4_count_flows (pntoh_ipv4_session_t session)
Returns the total count of flows stored in the global hash table.
pntoh_ipv4_session_t ntoh_ipv4_new_session (unsigned int max_flows, unsigned long max_mem, unsigned int *error)
Creates a new session with independent parameters to reassemble TCP segments.
void ntoh_ipv4_free_session (pntoh_ipv4_session_t session)
Releases all resources used by an IPv4 session.
void ntoh_ipv4_init (void)
Initializes the IPv4 defragmentation.
void ntoh_ipv4_exit (void)
Flush all IPv4 sessions and release all resources.
Macro Definition Documentation
#define __FAVOR_BSD
Definition at line 31 of file ipv4defrag.c.
#define IS_SET (a, b) (a & b)
Definition at line 48 of file ipv4defrag.c.
Referenced by ntoh_ipv4_add_fragment().
#define NTOH_GET_IPV4_FRAGMENT_OFFSET (offset) (8*(ntohs(offset)&IP_OFFMASK))
Definition at line 47 of file ipv4defrag.c.
Referenced by ntoh_ipv4_add_fragment().
Function Documentation
int ntoh_ipv4_add_fragment (pntoh_ipv4_session_t session, pntoh_ipv4_flow_t flow, struct ip * iphdr, size_t len)
Adds a new IPv4 fragment to a given flow.
Parameters
flow Flow where the new fragment will be added
iphdr IPv4 Header of the fragment
len Length of the fragment (IPv4 header + payload)
Returns
NTOH_OK on success, or error code when it fails
Definition at line 293 of file ipv4defrag.c.
References ntoh_ipv4_tuple4_t::destination, ntoh_ipv4_flow_t::final_iphdr, ntoh_ipv4_flow_t::fragments, ntoh_ipv4_flow_t::ident, IS_SET, ntoh_ipv4_flow_t::last_activ, ntoh_ipv4_flow_t::lock, lock_access(), MAX_DATAGRAM_LENGTH, ntoh_ipv4_flow_t::meat, MIN_IPV4_FRAGMENT_LENGTH, NTOH_GET_IPV4_FRAGMENT_OFFSET, NTOH_INCORRECT_IP_HEADER_LENGTH, NTOH_INCORRECT_IPHEADER, NTOH_INCORRECT_LENGTH, NTOH_INCORRECT_SESSION, NTOH_IP_ADDRESSES_MISMATCH, NTOH_IP_FRAGMENT_OVERRUN, NTOH_IP_INCORRECT_FLOW, NTOH_NO_ENOUGH_DATA, NTOH_NOT_AN_IP_FRAGMENT, NTOH_NOT_INITIALIZED, NTOH_NOT_IPV4, NTOH_OK, NTOH_REASON_DEFRAGMENTED_DATAGRAM, NTOH_TOO_LOW_IP_FRAGMENT_LENGTH, ntoh_ipv4_tuple4_t::source, ntoh_ipv4_flow_t::total, and unlock_access().
unsigned int ntoh_ipv4_count_flows (pntoh_ipv4_session_t session)
Returns the total count of flows stored in the global hash table.
Returns
Total count of stored flows
Definition at line 415 of file ipv4defrag.c.
References htable_count(), lock_access(), and unlock_access().
void ntoh_ipv4_exit (void)
Flush all IPv4 sessions and release all resources.
Definition at line 598 of file ipv4defrag.c.
References free_lockaccess(), lock_access(), and unlock_access().
Referenced by ntoh_exit().
pntoh_ipv4_flow_t ntoh_ipv4_find_flow (pntoh_ipv4_session_t session, pntoh_ipv4_tuple4_t tuple4)
Finds an IP flow.
Parameters
tuple4 Flow information
Returns
Pointer to the flow on success or 0 when fails
Definition at line 94 of file ipv4defrag.c.
References htable_find(), lock_access(), and unlock_access().
void ntoh_ipv4_free_flow (pntoh_ipv4_session_t session, pntoh_ipv4_flow_t * flow, unsigned short reason)
Frees an IPv4 flow.
Parameters
flow IPv4 flow to be freed
reason Why has been freed the flow?
Definition at line 278 of file ipv4defrag.c.
References lock_access(), and unlock_access().
void ntoh_ipv4_free_session (pntoh_ipv4_session_t session)
Releases all resources used by an IPv4 session.
Parameters
session Session to be released
Definition at line 571 of file ipv4defrag.c.
References lock_access(), and unlock_access().
unsigned int ntoh_ipv4_get_size (pntoh_ipv4_session_t session)
API to get the size of the flows table (max allowed flows)
Gets the size of the flows table (max allowed flows)
Definition at line 66 of file ipv4defrag.c.
References lock_access(), and unlock_access().
unsigned int ntoh_ipv4_get_tuple4 (struct ip * ip, pntoh_ipv4_tuple4_t tuple)
API to get a tuple4.
Gets the tuple4 of a IPv4 flow.
Definition at line 81 of file ipv4defrag.c.
References ntoh_ipv4_tuple4_t::destination, ntoh_ipv4_tuple4_t::id, NTOH_ERROR_PARAMS, NTOH_OK, ntoh_ipv4_tuple4_t::protocol, and ntoh_ipv4_tuple4_t::source.
void ntoh_ipv4_init (void)
Initializes the IPv4 defragmentation.
Definition at line 585 of file ipv4defrag.c.
Referenced by ntoh_init(), and ntoh_ipv4_new_session().
pntoh_ipv4_flow_t ntoh_ipv4_new_flow (pntoh_ipv4_session_t session, pntoh_ipv4_tuple4_t tuple4, pipv4_dfcallback_t function, void * udata, unsigned int * error)
Adds a new IPv4 flow.
Parameters
tuple4 Flow information
function User defined function to receive defragmented datagrams
count_max Max. fragments allowed
udata User defined data associated with this flow
Returns
A pointer to the new created flow
Definition at line 113 of file ipv4defrag.c.
References ntoh_ipv4_flow_t::function, htable_insert(), ntoh_ipv4_flow_t::ident, ntoh_ipv4_flow_t::key, ntoh_ipv4_flow_t::last_activ, ntoh_ipv4_flow_t::lock, lock_access(), ntoh_lock_t::mutex, NTOH_ERROR_INIT, NTOH_ERROR_NOSPACE, NTOH_ERROR_PARAMS, NTOH_OK, ntoh_lock_t::pcond, ntoh_ipv4_flow_t::udata, unlock_access(), and ntoh_lock_t::use.
pntoh_ipv4_session_t ntoh_ipv4_new_session (unsigned int max_flows, unsigned long max_mem, unsigned int * error)
Creates a new session with independent parameters to reassemble TCP segments.
Parameters
max_flows Max number of allowed flows in this session
max_mem Max. amount of memory used by the session
error Returned error code
Returns
A pointer to the new session or 0 when it fails
Definition at line 484 of file ipv4defrag.c.
References DEFAULT_IPV4_MAX_FLOWS, DEFAULT_IPV4_MAX_FRAGMENTS, htable_map(), lock_access(), NTOH_ERROR_NOMEM, ntoh_ipv4_init(), NTOH_OK, and unlock_access().
Variable Documentation
unsigned short init
Definition at line 42 of file ipv4defrag.c.
ntoh_lock_t lock
Definition at line 44 of file ipv4defrag.c.
pntoh_ipv4_session_t sessions_list
Definition at line 43 of file ipv4defrag.c.