libntoh: libntoh/libntoh.c File Reference
libntoh.c File Reference
#include <libntoh.h>
Macros
#define VERSION "0.4a"
Functions
const char * ntoh_version (void)
Header files.
const char * ntoh_get_retval_desc (int val)
Returns the description string of ntoh_add_tcpsegment and ntoh_add_ipv4fragment.
const char * ntoh_get_reason (unsigned int val)
Returns the description string about why a segment/fragment has been sent to the user.
const char * ntoh_get_errdesc (unsigned int val)
Returns the description of an error.
void ntoh_init (void)
Initializes the library (TCP and IPv4)
void ntoh_exit (void)
Releases all resources.
Macro Definition Documentation
#define VERSION "0.4a"
Definition at line 39 of file libntoh.c.
Referenced by ntoh_version().
Function Documentation
void ntoh_exit (void)
Releases all resources.
Definition at line 144 of file libntoh.c.
References ntoh_ipv4_exit(), and ntoh_tcp_exit().
const char* ntoh_get_errdesc (unsigned int val)
Returns the description of an error.
Parameters
val Error code
Returns
Description string or 0 if val is not found
Definition at line 130 of file libntoh.c.
const char* ntoh_get_reason (unsigned int val)
Returns the description string about why a segment/fragment has been sent to the user.
Parameters
val
Returns
Description string or 0 if val is not found
Definition at line 122 of file libntoh.c.
const char* ntoh_get_retval_desc (int val)
Returns the description string of ntoh_add_tcpsegment and ntoh_add_ipv4fragment.
Parameters
val Value returned by those functions
Returns
Description string or 0 if val is not found
Definition at line 112 of file libntoh.c.
void ntoh_init (void)
Initializes the library (TCP and IPv4)
Definition at line 138 of file libntoh.c.
References ntoh_ipv4_init(), and ntoh_tcp_init().
const char* ntoh_version (void)
Header files.
Returns library version
Returns
The version of the library
Definition at line 107 of file libntoh.c.
References VERSION.