libntoh: libntoh/tcpreassembly.c File Reference
tcpreassembly.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/time.h>
#include <libntoh.h>
Macros
#define IS_TIMEWAIT(peer, side) (peer.status == DEFAULT_TCP_TIMEWAIT_TIMEOUT || side.status == DEFAULT_TCP_TIMEWAIT_TIMEOUT)
#define IS_FINWAIT2(peer, side) (peer.status == NTOH_STATUS_FINWAIT2 || side.status == NTOH_STATUS_FINWAIT2)
Functions
const char * ntoh_tcp_get_status (unsigned int status)
API to get the string description associated to the given value corresponding with a TCP status.
unsigned int ntoh_tcp_get_tuple5 (struct ip *ip, struct tcphdr *tcp, pntoh_tcp_tuple5_t tuple)
API to get a tuple5.
unsigned int ntoh_tcp_get_size (pntoh_tcp_session_t session)
API to get the size of the sessions table (max allowed streams)
pntoh_tcp_session_t ntoh_tcp_new_session (unsigned int max_streams, unsigned int max_timewait, unsigned int *error)
API to create a new session and add it to the global sessions list.
void ntoh_tcp_free_session (pntoh_tcp_session_t session)
API to free a TCP session (wrapper)
void ntoh_tcp_free_stream (pntoh_tcp_session_t session, pntoh_tcp_stream_t *stream, int reason, int extra)
API to free a TCP stream (wrapper)
void ntoh_tcp_exit (void)
API to release all used TCP resources (sessions and streams)
void ntoh_tcp_init (void)
API to initialize the global structure.
pntoh_tcp_stream_t ntoh_tcp_find_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5)
API to look for a TCP stream identified by 'tuple5'.
pntoh_tcp_stream_t ntoh_tcp_new_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5, pntoh_tcp_callback_t function, void *udata, unsigned int *error)
API to create a new TCP stream and add it to the given session.
unsigned int ntoh_tcp_count_streams (pntoh_tcp_session_t session)
API to get the amount of streams stored in a session.
int ntoh_tcp_add_segment (pntoh_tcp_session_t session, pntoh_tcp_stream_t stream, struct ip *ip, size_t len, void *udata)
API for add an incoming segment.
Macro Definition Documentation
#define IS_FINWAIT2 (peer, side) (peer.status == NTOH_STATUS_FINWAIT2 || side.status == NTOH_STATUS_FINWAIT2)
#define IS_TIMEWAIT (peer, side) (peer.status == DEFAULT_TCP_TIMEWAIT_TIMEOUT || side.status == DEFAULT_TCP_TIMEWAIT_TIMEOUT)
Definition at line 45 of file tcpreassembly.c.
Function Documentation
int ntoh_tcp_add_segment (pntoh_tcp_session_t session, pntoh_tcp_stream_t stream, struct ip * ip, size_t len, void * udata)
API for add an incoming segment.
Adds a new segment to a given stream.
Definition at line 1088 of file tcpreassembly.c.
References ntoh_tcp_peer_t::ian, ntoh_tcp_peer_t::isn, ntoh_tcp_peer_t::lastts, lock_access(), ntoh_tcp_peer_t::next_seq, NTOH_ERROR_PARAMS, NTOH_HANDSHAKE_FAILED, NTOH_INCORRECT_IP_HEADER_LENGTH, NTOH_INCORRECT_IPHEADER, NTOH_INCORRECT_LENGTH, NTOH_INVALID_FLAGS, NTOH_IP_ADDRESSES_MISMATCH, NTOH_NO_ENOUGH_DATA, NTOH_NOT_IPV4, NTOH_NOT_TCP, NTOH_OK, NTOH_PAWS_FAILED, NTOH_REASON_CLOSED, NTOH_REASON_ESTABLISHED, NTOH_REASON_SYNC, NTOH_STATUS_CLOSED, NTOH_STATUS_ESTABLISHED, NTOH_STATUS_SYNRCV, NTOH_STATUS_SYNSENT, NTOH_SYNCHRONIZING, NTOH_TCP_PORTS_MISMATCH, NTOH_TOO_LOW_ACK_NUMBER, NTOH_TOO_LOW_SEQ_NUMBER, ntoh_tcp_peer_t::receive, and unlock_access().
unsigned int ntoh_tcp_count_streams (pntoh_tcp_session_t session)
API to get the amount of streams stored in a session.
Returns the total count of TCP streams stored in the global hash table.
Definition at line 625 of file tcpreassembly.c.
References htable_count(), lock_access(), and unlock_access().
void ntoh_tcp_exit (void)
API to release all used TCP resources (sessions and streams)
Releases all resources used by TCP reassembly.
Definition at line 474 of file tcpreassembly.c.
References free_lockaccess(), lock_access(), and unlock_access().
Referenced by ntoh_exit().
pntoh_tcp_stream_t ntoh_tcp_find_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5)
API to look for a TCP stream identified by 'tuple5'.
Finds a TCP stream.
Definition at line 509 of file tcpreassembly.c.
References ntoh_tcp_tuple5_t::destination, ntoh_tcp_tuple5_t::dport, htable_find(), lock_access(), ntoh_tcp_tuple5_t::protocol, ntoh_tcp_tuple5_t::source, ntoh_tcp_tuple5_t::sport, and unlock_access().
void ntoh_tcp_free_session (pntoh_tcp_session_t session)
API to free a TCP session (wrapper)
Releases all resources used by a session.
Definition at line 442 of file tcpreassembly.c.
References lock_access(), and unlock_access().
void ntoh_tcp_free_stream (pntoh_tcp_session_t session, pntoh_tcp_stream_t * stream, int reason, int extra)
API to free a TCP stream (wrapper)
Frees a given TCP stream.
Definition at line 458 of file tcpreassembly.c.
References lock_access(), and unlock_access().
unsigned int ntoh_tcp_get_size (pntoh_tcp_session_t session)
API to get the size of the sessions table (max allowed streams)
Gets the size of the sessions table (max allowed streams)
Definition at line 376 of file tcpreassembly.c.
References lock_access(), and unlock_access().
const char* ntoh_tcp_get_status (unsigned int status)
API to get the string description associated to the given value corresponding with a TCP status.
Get the status string of a stream/peer.
Definition at line 63 of file tcpreassembly.c.
References NTOH_STATUS_TIMEWAIT.
unsigned int ntoh_tcp_get_tuple5 (struct ip * ip, struct tcphdr * tcp, pntoh_tcp_tuple5_t tuple)
API to get a tuple5.
Gets the tuple5 of a TCP/IPv4 stream.
Definition at line 361 of file tcpreassembly.c.
References ntoh_tcp_tuple5_t::destination, ntoh_tcp_tuple5_t::dport, NTOH_ERROR_PARAMS, NTOH_OK, ntoh_tcp_tuple5_t::protocol, ntoh_tcp_tuple5_t::source, and ntoh_tcp_tuple5_t::sport.
void ntoh_tcp_init (void)
API to initialize the global structure.
Initializes all needed resources for TCP reassembly.
Definition at line 494 of file tcpreassembly.c.
Referenced by ntoh_init(), and ntoh_tcp_new_session().
pntoh_tcp_session_t ntoh_tcp_new_session (unsigned int max_streams, unsigned int max_timewait, unsigned int * error)
API to create a new session and add it to the global sessions list.
Creates a new session with independent parameters to reassemble TCP segments.
Definition at line 391 of file tcpreassembly.c.
References DEFAULT_TCP_MAX_STREAMS, DEFAULT_TCP_MAX_TIMEWAIT_STREAMS, htable_map(), lock_access(), NTOH_ERROR_NOMEM, NTOH_OK, ntoh_tcp_init(), and unlock_access().
pntoh_tcp_stream_t ntoh_tcp_new_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5, pntoh_tcp_callback_t function, void * udata, unsigned int * error)
API to create a new TCP stream and add it to the given session.
Adds a new TCP stream.
Definition at line 541 of file tcpreassembly.c.
References ntoh_tcp_tuple5_t::destination, ntoh_tcp_tuple5_t::dport, htable_insert(), lock_access(), NTOH_ERROR_INVALID_TUPLE5, NTOH_ERROR_NOFUNCTION, NTOH_ERROR_NOKEY, NTOH_ERROR_NOMEM, NTOH_ERROR_NOSPACE, NTOH_ERROR_PARAMS, NTOH_OK, NTOH_STATUS_CLOSED, ntoh_tcp_tuple5_t::source, ntoh_tcp_tuple5_t::sport, and unlock_access().
Variable Documentation
unsigned short init
Definition at line 40 of file tcpreassembly.c.
ntoh_lock_t lock
Definition at line 42 of file tcpreassembly.c.
pntoh_tcp_session_t sessions_list
Definition at line 41 of file tcpreassembly.c.