libntoh: libntoh/inc/tcpreassembly.h File Reference
tcpreassembly.h File Reference
#include <netinet/ip.h>
#include <netinet/tcp.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include "sfhash.h"
Data Structures
struct ntoh_tcp_tuple5_t
data to generate the connection key
struct pntoh_tcp_segment_t
data sent to user-function
struct ntoh_tcp_peer_t
peer information
struct pntoh_tcp_stream_t
connection data
struct pntoh_tcp_session_t
TCP session data.
Macros
#define __FAVOR_BSD
#define DEFAULT_TCP_MAX_STREAMS 1024
max allowed connections
#define DEFAULT_TCP_SYN_RETRIES 5
max SYN retries
#define DEFAULT_TCP_SYNACK_RETRIES 5
max SYN/ACK retries
#define DEFAULT_TCP_SYNSENT_TIMEOUT 5
SYN/ACK timeout.
#define DEFAULT_TCP_SYNRCV_TIMEOUT 5
ACK -> SYN timeout.
#define DEFAULT_TCP_ESTABLISHED_TIMEOUT 60
max. idle time for established connections
#define DEFAULT_TCP_FINWAIT2_TIMEOUT 60
max. idle time for "closed" connections
#define DEFAULT_TCP_TIMEWAIT_TIMEOUT 2*DEFAULT_TCP_ESTABLISHED_TIMEOUT
Default timeout for TIMEWAIT tcp connections.
#define DEFAULT_TCP_MAX_TIMEWAIT_STREAMS(max) (max>0?max/3:DEFAULT_TCP_MAX_STREAMS/3)
Macro to set the default TIMEWAIT for new connections.
Typedefs
typedef unsigned int ntoh_tcp_key_t
key to identify connections
typedef struct ntoh_tcp_tuple5_t * pntoh_tcp_tuple5_t
typedef struct ntoh_tcp_peer_t * pntoh_tcp_peer_t
typedef htable_t tcprs_streams_table_t
typedef phtable_t ptcprs_streams_table_t
typedef void(* pntoh_tcp_callback_t)(pntoh_tcp_stream_t, pntoh_tcp_peer_t, pntoh_tcp_peer_t, pntoh_tcp_segment_t, int, int)
Enumerations
enum _ntoh_tcp_status_ {
NTOH_STATUS_CLOSED = 0, NTOH_STATUS_LISTEN, NTOH_STATUS_SYNSENT, NTOH_STATUS_SYNRCV,
NTOH_STATUS_ESTABLISHED, NTOH_STATUS_CLOSING, NTOH_STATUS_CLOSEWAIT, NTOH_STATUS_FINWAIT1,
NTOH_STATUS_FINWAIT2, NTOH_STATUS_LASTACK, NTOH_STATUS_TIMEWAIT
}
connection status
enum tcprs_who_closed { NTOH_CLOSEDBY_UNKNOWN = 0, NTOH_CLOSEDBY_CLIENT, NTOH_CLOSEDBY_SERVER }
who closed the connection?
Functions
void ntoh_tcp_init (void)
Initializes all needed resources for TCP reassembly.
void ntoh_tcp_exit (void)
Releases all resources used by TCP reassembly.
pntoh_tcp_session_t ntoh_tcp_new_session (unsigned int max_streams, unsigned int max_timewait, unsigned int *error)
Creates a new session with independent parameters to reassemble TCP segments.
void ntoh_tcp_free_session (pntoh_tcp_session_t session)
Releases all resources used by a session.
void ntoh_tcp_free_stream (pntoh_tcp_session_t session, pntoh_tcp_stream_t *stream, int reason, int extra)
Frees a given TCP stream.
pntoh_tcp_stream_t ntoh_tcp_find_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5)
Finds a TCP stream.
pntoh_tcp_stream_t ntoh_tcp_new_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5, pntoh_tcp_callback_t function, void *udata, unsigned int *error)
Adds a new TCP stream.
unsigned int ntoh_tcp_count_streams (pntoh_tcp_session_t session)
Returns the total count of TCP streams stored in the global hash table.
int ntoh_tcp_add_segment (pntoh_tcp_session_t session, pntoh_tcp_stream_t stream, struct ip *ip, size_t len, void *udata)
Adds a new segment to a given stream.
const char * ntoh_tcp_get_status (unsigned int status)
Get the status string of a stream/peer.
unsigned int ntoh_tcp_get_size (pntoh_tcp_session_t session)
Gets the size of the sessions table (max allowed streams)
unsigned int ntoh_tcp_get_tuple5 (struct ip *ip, struct tcphdr *tcp, pntoh_tcp_tuple5_t tuple)
Gets the tuple5 of a TCP/IPv4 stream.
Macro Definition Documentation
#define __FAVOR_BSD
Definition at line 34 of file tcpreassembly.h.
#define DEFAULT_TCP_ESTABLISHED_TIMEOUT 60
max. idle time for established connections
Definition at line 223 of file tcpreassembly.h.
#define DEFAULT_TCP_FINWAIT2_TIMEOUT 60
max. idle time for "closed" connections
Definition at line 228 of file tcpreassembly.h.
#define DEFAULT_TCP_MAX_STREAMS 1024
max allowed connections
Definition at line 198 of file tcpreassembly.h.
Referenced by ntoh_tcp_new_session().
#define DEFAULT_TCP_MAX_TIMEWAIT_STREAMS (max) (max>0?max/3:DEFAULT_TCP_MAX_STREAMS/3)
Macro to set the default TIMEWAIT for new connections.
Definition at line 238 of file tcpreassembly.h.
Referenced by ntoh_tcp_new_session().
#define DEFAULT_TCP_SYN_RETRIES 5
max SYN retries
Definition at line 203 of file tcpreassembly.h.
#define DEFAULT_TCP_SYNACK_RETRIES 5
max SYN/ACK retries
Definition at line 208 of file tcpreassembly.h.
#define DEFAULT_TCP_SYNRCV_TIMEOUT 5
ACK -> SYN timeout.
Definition at line 218 of file tcpreassembly.h.
#define DEFAULT_TCP_SYNSENT_TIMEOUT 5
SYN/ACK timeout.
Definition at line 213 of file tcpreassembly.h.
#define DEFAULT_TCP_TIMEWAIT_TIMEOUT 2*DEFAULT_TCP_ESTABLISHED_TIMEOUT
Default timeout for TIMEWAIT tcp connections.
Definition at line 233 of file tcpreassembly.h.
Typedef Documentation
typedef unsigned int ntoh_tcp_key_t
key to identify connections
Definition at line 68 of file tcpreassembly.h.
typedef void(* pntoh_tcp_callback_t)(pntoh_tcp_stream_t, pntoh_tcp_peer_t, pntoh_tcp_peer_t, pntoh_tcp_segment_t, int, int)
Definition at line 194 of file tcpreassembly.h.
typedef struct ntoh_tcp_peer_t * pntoh_tcp_peer_t
typedef struct ntoh_tcp_tuple5_t * pntoh_tcp_tuple5_t
typedef phtable_t ptcprs_streams_table_t
Definition at line 171 of file tcpreassembly.h.
typedef htable_t tcprs_streams_table_t
Definition at line 170 of file tcpreassembly.h.
Enumeration Type Documentation
enum _ntoh_tcp_status_
connection status
Enumerator:
NTOH_STATUS_CLOSED
NTOH_STATUS_LISTEN
NTOH_STATUS_SYNSENT
NTOH_STATUS_SYNRCV
NTOH_STATUS_ESTABLISHED
NTOH_STATUS_CLOSING
NTOH_STATUS_CLOSEWAIT
NTOH_STATUS_FINWAIT1
NTOH_STATUS_FINWAIT2
NTOH_STATUS_LASTACK
NTOH_STATUS_TIMEWAIT
Definition at line 44 of file tcpreassembly.h.
enum tcprs_who_closed
who closed the connection?
Enumerator:
NTOH_CLOSEDBY_UNKNOWN
NTOH_CLOSEDBY_CLIENT
NTOH_CLOSEDBY_SERVER
Definition at line 60 of file tcpreassembly.h.
Function Documentation
int ntoh_tcp_add_segment (pntoh_tcp_session_t session, pntoh_tcp_stream_t stream, struct ip * ip, size_t len, void * udata)
Adds a new segment to a given stream.
Parameters
session TCP Session
stream Pointer to the stream
ip_hdr IP Header
len Total length of this segment
udata Used data associated with this segment
Returns
NTOH_OK on success or the corresponding error code
Definition at line 1088 of file tcpreassembly.c.
References ntoh_tcp_peer_t::ian, ntoh_tcp_peer_t::isn, ntoh_tcp_peer_t::lastts, lock_access(), ntoh_tcp_peer_t::next_seq, NTOH_ERROR_PARAMS, NTOH_HANDSHAKE_FAILED, NTOH_INCORRECT_IP_HEADER_LENGTH, NTOH_INCORRECT_IPHEADER, NTOH_INCORRECT_LENGTH, NTOH_INVALID_FLAGS, NTOH_IP_ADDRESSES_MISMATCH, NTOH_NO_ENOUGH_DATA, NTOH_NOT_IPV4, NTOH_NOT_TCP, NTOH_OK, NTOH_PAWS_FAILED, NTOH_REASON_CLOSED, NTOH_REASON_ESTABLISHED, NTOH_REASON_SYNC, NTOH_STATUS_CLOSED, NTOH_STATUS_ESTABLISHED, NTOH_STATUS_SYNRCV, NTOH_STATUS_SYNSENT, NTOH_SYNCHRONIZING, NTOH_TCP_PORTS_MISMATCH, NTOH_TOO_LOW_ACK_NUMBER, NTOH_TOO_LOW_SEQ_NUMBER, ntoh_tcp_peer_t::receive, and unlock_access().
unsigned int ntoh_tcp_count_streams (pntoh_tcp_session_t session)
Returns the total count of TCP streams stored in the global hash table.
Parameters
session TCP Session
Returns
Total count of stored streams
Definition at line 625 of file tcpreassembly.c.
References htable_count(), lock_access(), and unlock_access().
void ntoh_tcp_exit (void)
Releases all resources used by TCP reassembly.
Definition at line 474 of file tcpreassembly.c.
References free_lockaccess(), lock_access(), and unlock_access().
Referenced by ntoh_exit().
pntoh_tcp_stream_t ntoh_tcp_find_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5)
Finds a TCP stream.
Parameters
session TCP Session
tuple5 Stream information
Returns
Pointer to the stream on success or 0 when fails
Definition at line 509 of file tcpreassembly.c.
References ntoh_tcp_tuple5_t::destination, ntoh_tcp_tuple5_t::dport, htable_find(), lock_access(), ntoh_tcp_tuple5_t::protocol, ntoh_tcp_tuple5_t::source, ntoh_tcp_tuple5_t::sport, and unlock_access().
void ntoh_tcp_free_session (pntoh_tcp_session_t session)
Releases all resources used by a session.
Parameters
session Session to be released
Definition at line 442 of file tcpreassembly.c.
References lock_access(), and unlock_access().
void ntoh_tcp_free_stream (pntoh_tcp_session_t session, pntoh_tcp_stream_t * stream, int reason, int extra)
Frees a given TCP stream.
Parameters
session Pointer to the session
stream Pointer to the stream
reason Value to be sent to the user defined function
extra Value to be sent to the user defined function
Definition at line 458 of file tcpreassembly.c.
References lock_access(), and unlock_access().
unsigned int ntoh_tcp_get_size (pntoh_tcp_session_t session)
Gets the size of the sessions table (max allowed streams)
Parameters
session TCP Session
Returns
The max. amount of TCP streams that can be stored , or zero on error
Definition at line 376 of file tcpreassembly.c.
References lock_access(), and unlock_access().
const char* ntoh_tcp_get_status (unsigned int status)
Get the status string of a stream/peer.
Parameters
status Status id
Returns
Status string on success or 0 when fails
Definition at line 63 of file tcpreassembly.c.
References NTOH_STATUS_TIMEWAIT.
unsigned int ntoh_tcp_get_tuple5 (struct ip * ip, struct tcphdr * tcp, pntoh_tcp_tuple5_t tuple)
Gets the tuple5 of a TCP/IPv4 stream.
Parameters
ip Pointer to the IPv4 header
tcp Pointer to the TCP header
tuple Pointer to the output tuple5 struct
Returns
NTOH_OK on success or the corresponding error code
Definition at line 361 of file tcpreassembly.c.
References ntoh_tcp_tuple5_t::destination, ntoh_tcp_tuple5_t::dport, NTOH_ERROR_PARAMS, NTOH_OK, ntoh_tcp_tuple5_t::protocol, ntoh_tcp_tuple5_t::source, and ntoh_tcp_tuple5_t::sport.
void ntoh_tcp_init (void)
Initializes all needed resources for TCP reassembly.
Definition at line 494 of file tcpreassembly.c.
Referenced by ntoh_init(), and ntoh_tcp_new_session().
pntoh_tcp_session_t ntoh_tcp_new_session (unsigned int max_streams, unsigned int max_timewait, unsigned int * error)
Creates a new session with independent parameters to reassemble TCP segments.
Parameters
max_streams Max number of allowed streams in this session
max_timewait Max idle time fo TIME-WAIT connections (global)
error Returned error code
Returns
A pointer to the new session or 0 when it fails
Definition at line 391 of file tcpreassembly.c.
References DEFAULT_TCP_MAX_STREAMS, DEFAULT_TCP_MAX_TIMEWAIT_STREAMS, htable_map(), lock_access(), NTOH_ERROR_NOMEM, NTOH_OK, ntoh_tcp_init(), and unlock_access().
pntoh_tcp_stream_t ntoh_tcp_new_stream (pntoh_tcp_session_t session, pntoh_tcp_tuple5_t tuple5, pntoh_tcp_callback_t function, void * udata, unsigned int * error)
Adds a new TCP stream.
Parameters
session TCP Session
tuple5 Stream information
function User defined function to receive the segments of this stream
udata User-defined data to be linked to the new stream
error Returned error code
Returns
A pointer to the new stream on success or 0 when fails
Definition at line 541 of file tcpreassembly.c.
References ntoh_tcp_tuple5_t::destination, ntoh_tcp_tuple5_t::dport, htable_insert(), lock_access(), NTOH_ERROR_INVALID_TUPLE5, NTOH_ERROR_NOFUNCTION, NTOH_ERROR_NOKEY, NTOH_ERROR_NOMEM, NTOH_ERROR_NOSPACE, NTOH_ERROR_PARAMS, NTOH_OK, NTOH_STATUS_CLOSED, ntoh_tcp_tuple5_t::source, ntoh_tcp_tuple5_t::sport, and unlock_access().